//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _8_DatabaseWebService.service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="service.DatabaseWebServiceSoap")]
    public interface DatabaseWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_Size", ReplyAction="*")]
        int get_Size();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/get_Size", ReplyAction="*")]
        System.IAsyncResult Beginget_Size(System.AsyncCallback callback, object asyncState);
        
        int Endget_Size(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name keys from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search", ReplyAction="*")]
        _8_DatabaseWebService.service.SearchResponse Search(_8_DatabaseWebService.service.SearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Search", ReplyAction="*")]
        System.IAsyncResult BeginSearch(_8_DatabaseWebService.service.SearchRequest request, System.AsyncCallback callback, object asyncState);
        
        _8_DatabaseWebService.service.SearchResponse EndSearch(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name tuple from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Enter", ReplyAction="*")]
        _8_DatabaseWebService.service.EnterResponse Enter(_8_DatabaseWebService.service.EnterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Enter", ReplyAction="*")]
        System.IAsyncResult BeginEnter(_8_DatabaseWebService.service.EnterRequest request, System.AsyncCallback callback, object asyncState);
        
        _8_DatabaseWebService.service.EnterResponse EndEnter(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name keys from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Remove", ReplyAction="*")]
        _8_DatabaseWebService.service.RemoveResponse Remove(_8_DatabaseWebService.service.RemoveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Remove", ReplyAction="*")]
        System.IAsyncResult BeginRemove(_8_DatabaseWebService.service.RemoveRequest request, System.AsyncCallback callback, object asyncState);
        
        _8_DatabaseWebService.service.RemoveResponse EndRemove(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Search", Namespace="http://tempuri.org/", Order=0)]
        public _8_DatabaseWebService.service.SearchRequestBody Body;
        
        public SearchRequest() {
        }
        
        public SearchRequest(_8_DatabaseWebService.service.SearchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _8_DatabaseWebService.service.ArrayOfString keys;
        
        public SearchRequestBody() {
        }
        
        public SearchRequestBody(_8_DatabaseWebService.service.ArrayOfString keys) {
            this.keys = keys;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchResponse", Namespace="http://tempuri.org/", Order=0)]
        public _8_DatabaseWebService.service.SearchResponseBody Body;
        
        public SearchResponse() {
        }
        
        public SearchResponse(_8_DatabaseWebService.service.SearchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _8_DatabaseWebService.service.ArrayOfString[] SearchResult;
        
        public SearchResponseBody() {
        }
        
        public SearchResponseBody(_8_DatabaseWebService.service.ArrayOfString[] SearchResult) {
            this.SearchResult = SearchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Enter", Namespace="http://tempuri.org/", Order=0)]
        public _8_DatabaseWebService.service.EnterRequestBody Body;
        
        public EnterRequest() {
        }
        
        public EnterRequest(_8_DatabaseWebService.service.EnterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _8_DatabaseWebService.service.ArrayOfString tuple;
        
        public EnterRequestBody() {
        }
        
        public EnterRequestBody(_8_DatabaseWebService.service.ArrayOfString tuple) {
            this.tuple = tuple;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnterResponse", Namespace="http://tempuri.org/", Order=0)]
        public _8_DatabaseWebService.service.EnterResponseBody Body;
        
        public EnterResponse() {
        }
        
        public EnterResponse(_8_DatabaseWebService.service.EnterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EnterResult;
        
        public EnterResponseBody() {
        }
        
        public EnterResponseBody(bool EnterResult) {
            this.EnterResult = EnterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Remove", Namespace="http://tempuri.org/", Order=0)]
        public _8_DatabaseWebService.service.RemoveRequestBody Body;
        
        public RemoveRequest() {
        }
        
        public RemoveRequest(_8_DatabaseWebService.service.RemoveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _8_DatabaseWebService.service.ArrayOfString keys;
        
        public RemoveRequestBody() {
        }
        
        public RemoveRequestBody(_8_DatabaseWebService.service.ArrayOfString keys) {
            this.keys = keys;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveResponse", Namespace="http://tempuri.org/", Order=0)]
        public _8_DatabaseWebService.service.RemoveResponseBody Body;
        
        public RemoveResponse() {
        }
        
        public RemoveResponse(_8_DatabaseWebService.service.RemoveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RemoveResult;
        
        public RemoveResponseBody() {
        }
        
        public RemoveResponseBody(bool RemoveResult) {
            this.RemoveResult = RemoveResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface DatabaseWebServiceSoapChannel : _8_DatabaseWebService.service.DatabaseWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class get_SizeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public get_SizeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public _8_DatabaseWebService.service.ArrayOfString[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((_8_DatabaseWebService.service.ArrayOfString[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class EnterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public EnterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class RemoveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RemoveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class DatabaseWebServiceSoapClient : System.ServiceModel.ClientBase<_8_DatabaseWebService.service.DatabaseWebServiceSoap>, _8_DatabaseWebService.service.DatabaseWebServiceSoap {
        
        private BeginOperationDelegate onBeginget_SizeDelegate;
        
        private EndOperationDelegate onEndget_SizeDelegate;
        
        private System.Threading.SendOrPostCallback onget_SizeCompletedDelegate;
        
        private BeginOperationDelegate onBeginSearchDelegate;
        
        private EndOperationDelegate onEndSearchDelegate;
        
        private System.Threading.SendOrPostCallback onSearchCompletedDelegate;
        
        private BeginOperationDelegate onBeginEnterDelegate;
        
        private EndOperationDelegate onEndEnterDelegate;
        
        private System.Threading.SendOrPostCallback onEnterCompletedDelegate;
        
        private BeginOperationDelegate onBeginRemoveDelegate;
        
        private EndOperationDelegate onEndRemoveDelegate;
        
        private System.Threading.SendOrPostCallback onRemoveCompletedDelegate;
        
        public DatabaseWebServiceSoapClient() {
        }
        
        public DatabaseWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DatabaseWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<get_SizeCompletedEventArgs> get_SizeCompleted;
        
        public event System.EventHandler<SearchCompletedEventArgs> SearchCompleted;
        
        public event System.EventHandler<EnterCompletedEventArgs> EnterCompleted;
        
        public event System.EventHandler<RemoveCompletedEventArgs> RemoveCompleted;
        
        public int get_Size() {
            return base.Channel.get_Size();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginget_Size(System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginget_Size(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int Endget_Size(System.IAsyncResult result) {
            return base.Channel.Endget_Size(result);
        }
        
        private System.IAsyncResult OnBeginget_Size(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.Beginget_Size(callback, asyncState);
        }
        
        private object[] OnEndget_Size(System.IAsyncResult result) {
            int retVal = this.Endget_Size(result);
            return new object[] {
                    retVal};
        }
        
        private void Onget_SizeCompleted(object state) {
            if ((this.get_SizeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.get_SizeCompleted(this, new get_SizeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void get_SizeAsync() {
            this.get_SizeAsync(null);
        }
        
        public void get_SizeAsync(object userState) {
            if ((this.onBeginget_SizeDelegate == null)) {
                this.onBeginget_SizeDelegate = new BeginOperationDelegate(this.OnBeginget_Size);
            }
            if ((this.onEndget_SizeDelegate == null)) {
                this.onEndget_SizeDelegate = new EndOperationDelegate(this.OnEndget_Size);
            }
            if ((this.onget_SizeCompletedDelegate == null)) {
                this.onget_SizeCompletedDelegate = new System.Threading.SendOrPostCallback(this.Onget_SizeCompleted);
            }
            base.InvokeAsync(this.onBeginget_SizeDelegate, null, this.onEndget_SizeDelegate, this.onget_SizeCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _8_DatabaseWebService.service.SearchResponse _8_DatabaseWebService.service.DatabaseWebServiceSoap.Search(_8_DatabaseWebService.service.SearchRequest request) {
            return base.Channel.Search(request);
        }
        
        public _8_DatabaseWebService.service.ArrayOfString[] Search(_8_DatabaseWebService.service.ArrayOfString keys) {
            _8_DatabaseWebService.service.SearchRequest inValue = new _8_DatabaseWebService.service.SearchRequest();
            inValue.Body = new _8_DatabaseWebService.service.SearchRequestBody();
            inValue.Body.keys = keys;
            _8_DatabaseWebService.service.SearchResponse retVal = ((_8_DatabaseWebService.service.DatabaseWebServiceSoap)(this)).Search(inValue);
            return retVal.Body.SearchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult _8_DatabaseWebService.service.DatabaseWebServiceSoap.BeginSearch(_8_DatabaseWebService.service.SearchRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSearch(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSearch(_8_DatabaseWebService.service.ArrayOfString keys, System.AsyncCallback callback, object asyncState) {
            _8_DatabaseWebService.service.SearchRequest inValue = new _8_DatabaseWebService.service.SearchRequest();
            inValue.Body = new _8_DatabaseWebService.service.SearchRequestBody();
            inValue.Body.keys = keys;
            return ((_8_DatabaseWebService.service.DatabaseWebServiceSoap)(this)).BeginSearch(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _8_DatabaseWebService.service.SearchResponse _8_DatabaseWebService.service.DatabaseWebServiceSoap.EndSearch(System.IAsyncResult result) {
            return base.Channel.EndSearch(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public _8_DatabaseWebService.service.ArrayOfString[] EndSearch(System.IAsyncResult result) {
            _8_DatabaseWebService.service.SearchResponse retVal = ((_8_DatabaseWebService.service.DatabaseWebServiceSoap)(this)).EndSearch(result);
            return retVal.Body.SearchResult;
        }
        
        private System.IAsyncResult OnBeginSearch(object[] inValues, System.AsyncCallback callback, object asyncState) {
            _8_DatabaseWebService.service.ArrayOfString keys = ((_8_DatabaseWebService.service.ArrayOfString)(inValues[0]));
            return this.BeginSearch(keys, callback, asyncState);
        }
        
        private object[] OnEndSearch(System.IAsyncResult result) {
            _8_DatabaseWebService.service.ArrayOfString[] retVal = this.EndSearch(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSearchCompleted(object state) {
            if ((this.SearchCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SearchCompleted(this, new SearchCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SearchAsync(_8_DatabaseWebService.service.ArrayOfString keys) {
            this.SearchAsync(keys, null);
        }
        
        public void SearchAsync(_8_DatabaseWebService.service.ArrayOfString keys, object userState) {
            if ((this.onBeginSearchDelegate == null)) {
                this.onBeginSearchDelegate = new BeginOperationDelegate(this.OnBeginSearch);
            }
            if ((this.onEndSearchDelegate == null)) {
                this.onEndSearchDelegate = new EndOperationDelegate(this.OnEndSearch);
            }
            if ((this.onSearchCompletedDelegate == null)) {
                this.onSearchCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSearchCompleted);
            }
            base.InvokeAsync(this.onBeginSearchDelegate, new object[] {
                        keys}, this.onEndSearchDelegate, this.onSearchCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _8_DatabaseWebService.service.EnterResponse _8_DatabaseWebService.service.DatabaseWebServiceSoap.Enter(_8_DatabaseWebService.service.EnterRequest request) {
            return base.Channel.Enter(request);
        }
        
        public bool Enter(_8_DatabaseWebService.service.ArrayOfString tuple) {
            _8_DatabaseWebService.service.EnterRequest inValue = new _8_DatabaseWebService.service.EnterRequest();
            inValue.Body = new _8_DatabaseWebService.service.EnterRequestBody();
            inValue.Body.tuple = tuple;
            _8_DatabaseWebService.service.EnterResponse retVal = ((_8_DatabaseWebService.service.DatabaseWebServiceSoap)(this)).Enter(inValue);
            return retVal.Body.EnterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult _8_DatabaseWebService.service.DatabaseWebServiceSoap.BeginEnter(_8_DatabaseWebService.service.EnterRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEnter(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginEnter(_8_DatabaseWebService.service.ArrayOfString tuple, System.AsyncCallback callback, object asyncState) {
            _8_DatabaseWebService.service.EnterRequest inValue = new _8_DatabaseWebService.service.EnterRequest();
            inValue.Body = new _8_DatabaseWebService.service.EnterRequestBody();
            inValue.Body.tuple = tuple;
            return ((_8_DatabaseWebService.service.DatabaseWebServiceSoap)(this)).BeginEnter(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _8_DatabaseWebService.service.EnterResponse _8_DatabaseWebService.service.DatabaseWebServiceSoap.EndEnter(System.IAsyncResult result) {
            return base.Channel.EndEnter(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndEnter(System.IAsyncResult result) {
            _8_DatabaseWebService.service.EnterResponse retVal = ((_8_DatabaseWebService.service.DatabaseWebServiceSoap)(this)).EndEnter(result);
            return retVal.Body.EnterResult;
        }
        
        private System.IAsyncResult OnBeginEnter(object[] inValues, System.AsyncCallback callback, object asyncState) {
            _8_DatabaseWebService.service.ArrayOfString tuple = ((_8_DatabaseWebService.service.ArrayOfString)(inValues[0]));
            return this.BeginEnter(tuple, callback, asyncState);
        }
        
        private object[] OnEndEnter(System.IAsyncResult result) {
            bool retVal = this.EndEnter(result);
            return new object[] {
                    retVal};
        }
        
        private void OnEnterCompleted(object state) {
            if ((this.EnterCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EnterCompleted(this, new EnterCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EnterAsync(_8_DatabaseWebService.service.ArrayOfString tuple) {
            this.EnterAsync(tuple, null);
        }
        
        public void EnterAsync(_8_DatabaseWebService.service.ArrayOfString tuple, object userState) {
            if ((this.onBeginEnterDelegate == null)) {
                this.onBeginEnterDelegate = new BeginOperationDelegate(this.OnBeginEnter);
            }
            if ((this.onEndEnterDelegate == null)) {
                this.onEndEnterDelegate = new EndOperationDelegate(this.OnEndEnter);
            }
            if ((this.onEnterCompletedDelegate == null)) {
                this.onEnterCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEnterCompleted);
            }
            base.InvokeAsync(this.onBeginEnterDelegate, new object[] {
                        tuple}, this.onEndEnterDelegate, this.onEnterCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _8_DatabaseWebService.service.RemoveResponse _8_DatabaseWebService.service.DatabaseWebServiceSoap.Remove(_8_DatabaseWebService.service.RemoveRequest request) {
            return base.Channel.Remove(request);
        }
        
        public bool Remove(_8_DatabaseWebService.service.ArrayOfString keys) {
            _8_DatabaseWebService.service.RemoveRequest inValue = new _8_DatabaseWebService.service.RemoveRequest();
            inValue.Body = new _8_DatabaseWebService.service.RemoveRequestBody();
            inValue.Body.keys = keys;
            _8_DatabaseWebService.service.RemoveResponse retVal = ((_8_DatabaseWebService.service.DatabaseWebServiceSoap)(this)).Remove(inValue);
            return retVal.Body.RemoveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult _8_DatabaseWebService.service.DatabaseWebServiceSoap.BeginRemove(_8_DatabaseWebService.service.RemoveRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRemove(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginRemove(_8_DatabaseWebService.service.ArrayOfString keys, System.AsyncCallback callback, object asyncState) {
            _8_DatabaseWebService.service.RemoveRequest inValue = new _8_DatabaseWebService.service.RemoveRequest();
            inValue.Body = new _8_DatabaseWebService.service.RemoveRequestBody();
            inValue.Body.keys = keys;
            return ((_8_DatabaseWebService.service.DatabaseWebServiceSoap)(this)).BeginRemove(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _8_DatabaseWebService.service.RemoveResponse _8_DatabaseWebService.service.DatabaseWebServiceSoap.EndRemove(System.IAsyncResult result) {
            return base.Channel.EndRemove(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndRemove(System.IAsyncResult result) {
            _8_DatabaseWebService.service.RemoveResponse retVal = ((_8_DatabaseWebService.service.DatabaseWebServiceSoap)(this)).EndRemove(result);
            return retVal.Body.RemoveResult;
        }
        
        private System.IAsyncResult OnBeginRemove(object[] inValues, System.AsyncCallback callback, object asyncState) {
            _8_DatabaseWebService.service.ArrayOfString keys = ((_8_DatabaseWebService.service.ArrayOfString)(inValues[0]));
            return this.BeginRemove(keys, callback, asyncState);
        }
        
        private object[] OnEndRemove(System.IAsyncResult result) {
            bool retVal = this.EndRemove(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRemoveCompleted(object state) {
            if ((this.RemoveCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RemoveCompleted(this, new RemoveCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RemoveAsync(_8_DatabaseWebService.service.ArrayOfString keys) {
            this.RemoveAsync(keys, null);
        }
        
        public void RemoveAsync(_8_DatabaseWebService.service.ArrayOfString keys, object userState) {
            if ((this.onBeginRemoveDelegate == null)) {
                this.onBeginRemoveDelegate = new BeginOperationDelegate(this.OnBeginRemove);
            }
            if ((this.onEndRemoveDelegate == null)) {
                this.onEndRemoveDelegate = new EndOperationDelegate(this.OnEndRemove);
            }
            if ((this.onRemoveCompletedDelegate == null)) {
                this.onRemoveCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRemoveCompleted);
            }
            base.InvokeAsync(this.onBeginRemoveDelegate, new object[] {
                        keys}, this.onEndRemoveDelegate, this.onRemoveCompletedDelegate, userState);
        }
    }
}
