//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _6_DistributedWinner_Client.temperatures {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cs.rit.edu/axel/conversions/", ConfigurationName="temperatures.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://www.cs.rit.edu/axel/conversions/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cs.rit.edu/axel/conversions/HelloWorld", ReplyAction="*")]
        _6_DistributedWinner_Client.temperatures.HelloWorldResponse HelloWorld(_6_DistributedWinner_Client.temperatures.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cs.rit.edu/axel/conversions/Celsius", ReplyAction="*")]
        double Celsius(double fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cs.rit.edu/axel/conversions/Fahrenheit", ReplyAction="*")]
        double Fahrenheit(double celsius);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://www.cs.rit.edu/axel/conversions/", Order=0)]
        public _6_DistributedWinner_Client.temperatures.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(_6_DistributedWinner_Client.temperatures.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://www.cs.rit.edu/axel/conversions/", Order=0)]
        public _6_DistributedWinner_Client.temperatures.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(_6_DistributedWinner_Client.temperatures.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cs.rit.edu/axel/conversions/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface Service1SoapChannel : _6_DistributedWinner_Client.temperatures.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<_6_DistributedWinner_Client.temperatures.Service1Soap>, _6_DistributedWinner_Client.temperatures.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _6_DistributedWinner_Client.temperatures.HelloWorldResponse _6_DistributedWinner_Client.temperatures.Service1Soap.HelloWorld(_6_DistributedWinner_Client.temperatures.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            _6_DistributedWinner_Client.temperatures.HelloWorldRequest inValue = new _6_DistributedWinner_Client.temperatures.HelloWorldRequest();
            inValue.Body = new _6_DistributedWinner_Client.temperatures.HelloWorldRequestBody();
            _6_DistributedWinner_Client.temperatures.HelloWorldResponse retVal = ((_6_DistributedWinner_Client.temperatures.Service1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        public double Celsius(double fahrenheit) {
            return base.Channel.Celsius(fahrenheit);
        }
        
        public double Fahrenheit(double celsius) {
            return base.Channel.Fahrenheit(celsius);
        }
    }
}
