//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _6_DistributedWinner_Client.SelectingAWinnerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cs.rit.edu/axel/conversions/", ConfigurationName="SelectingAWinnerService.PlayerCellServiceSoap")]
    public interface PlayerCellServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://www.cs.rit.edu/axel/conversions/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cs.rit.edu/axel/conversions/HelloWorld", ReplyAction="*")]
        _6_DistributedWinner_Client.SelectingAWinnerService.HelloWorldResponse HelloWorld(_6_DistributedWinner_Client.SelectingAWinnerService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cs.rit.edu/axel/conversions/Login", ReplyAction="*")]
        int Login();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cs.rit.edu/axel/conversions/Get", ReplyAction="*")]
        int Get(int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cs.rit.edu/axel/conversions/Set", ReplyAction="*")]
        void Set(int playerId, int selection);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://www.cs.rit.edu/axel/conversions/", Order=0)]
        public _6_DistributedWinner_Client.SelectingAWinnerService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(_6_DistributedWinner_Client.SelectingAWinnerService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://www.cs.rit.edu/axel/conversions/", Order=0)]
        public _6_DistributedWinner_Client.SelectingAWinnerService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(_6_DistributedWinner_Client.SelectingAWinnerService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cs.rit.edu/axel/conversions/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface PlayerCellServiceSoapChannel : _6_DistributedWinner_Client.SelectingAWinnerService.PlayerCellServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class PlayerCellServiceSoapClient : System.ServiceModel.ClientBase<_6_DistributedWinner_Client.SelectingAWinnerService.PlayerCellServiceSoap>, _6_DistributedWinner_Client.SelectingAWinnerService.PlayerCellServiceSoap {
        
        public PlayerCellServiceSoapClient() {
        }
        
        public PlayerCellServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlayerCellServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerCellServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerCellServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _6_DistributedWinner_Client.SelectingAWinnerService.HelloWorldResponse _6_DistributedWinner_Client.SelectingAWinnerService.PlayerCellServiceSoap.HelloWorld(_6_DistributedWinner_Client.SelectingAWinnerService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            _6_DistributedWinner_Client.SelectingAWinnerService.HelloWorldRequest inValue = new _6_DistributedWinner_Client.SelectingAWinnerService.HelloWorldRequest();
            inValue.Body = new _6_DistributedWinner_Client.SelectingAWinnerService.HelloWorldRequestBody();
            _6_DistributedWinner_Client.SelectingAWinnerService.HelloWorldResponse retVal = ((_6_DistributedWinner_Client.SelectingAWinnerService.PlayerCellServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        public int Login() {
            return base.Channel.Login();
        }
        
        public int Get(int playerId) {
            return base.Channel.Get(playerId);
        }
        
        public void Set(int playerId, int selection) {
            base.Channel.Set(playerId, selection);
        }
    }
}
