//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _8_DatabaseWebService_RemoteDB._8_DatabaseWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="_8_DatabaseWebService.DatabaseWebServiceSoap")]
    public interface DatabaseWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_Size", ReplyAction="*")]
        int get_Size();
        
        // CODEGEN: Generating message contract since element name keys from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search", ReplyAction="*")]
        _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.SearchResponse Search(_8_DatabaseWebService_RemoteDB._8_DatabaseWebService.SearchRequest request);
        
        // CODEGEN: Generating message contract since element name tuple from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Enter", ReplyAction="*")]
        _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.EnterResponse Enter(_8_DatabaseWebService_RemoteDB._8_DatabaseWebService.EnterRequest request);
        
        // CODEGEN: Generating message contract since element name keys from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Remove", ReplyAction="*")]
        _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.RemoveResponse Remove(_8_DatabaseWebService_RemoteDB._8_DatabaseWebService.RemoveRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Search", Namespace="http://tempuri.org/", Order=0)]
        public _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.SearchRequestBody Body;
        
        public SearchRequest() {
        }
        
        public SearchRequest(_8_DatabaseWebService_RemoteDB._8_DatabaseWebService.SearchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.ArrayOfString keys;
        
        public SearchRequestBody() {
        }
        
        public SearchRequestBody(_8_DatabaseWebService_RemoteDB._8_DatabaseWebService.ArrayOfString keys) {
            this.keys = keys;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchResponse", Namespace="http://tempuri.org/", Order=0)]
        public _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.SearchResponseBody Body;
        
        public SearchResponse() {
        }
        
        public SearchResponse(_8_DatabaseWebService_RemoteDB._8_DatabaseWebService.SearchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.ArrayOfString[] SearchResult;
        
        public SearchResponseBody() {
        }
        
        public SearchResponseBody(_8_DatabaseWebService_RemoteDB._8_DatabaseWebService.ArrayOfString[] SearchResult) {
            this.SearchResult = SearchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Enter", Namespace="http://tempuri.org/", Order=0)]
        public _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.EnterRequestBody Body;
        
        public EnterRequest() {
        }
        
        public EnterRequest(_8_DatabaseWebService_RemoteDB._8_DatabaseWebService.EnterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.ArrayOfString tuple;
        
        public EnterRequestBody() {
        }
        
        public EnterRequestBody(_8_DatabaseWebService_RemoteDB._8_DatabaseWebService.ArrayOfString tuple) {
            this.tuple = tuple;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnterResponse", Namespace="http://tempuri.org/", Order=0)]
        public _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.EnterResponseBody Body;
        
        public EnterResponse() {
        }
        
        public EnterResponse(_8_DatabaseWebService_RemoteDB._8_DatabaseWebService.EnterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EnterResult;
        
        public EnterResponseBody() {
        }
        
        public EnterResponseBody(bool EnterResult) {
            this.EnterResult = EnterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Remove", Namespace="http://tempuri.org/", Order=0)]
        public _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.RemoveRequestBody Body;
        
        public RemoveRequest() {
        }
        
        public RemoveRequest(_8_DatabaseWebService_RemoteDB._8_DatabaseWebService.RemoveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.ArrayOfString keys;
        
        public RemoveRequestBody() {
        }
        
        public RemoveRequestBody(_8_DatabaseWebService_RemoteDB._8_DatabaseWebService.ArrayOfString keys) {
            this.keys = keys;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveResponse", Namespace="http://tempuri.org/", Order=0)]
        public _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.RemoveResponseBody Body;
        
        public RemoveResponse() {
        }
        
        public RemoveResponse(_8_DatabaseWebService_RemoteDB._8_DatabaseWebService.RemoveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RemoveResult;
        
        public RemoveResponseBody() {
        }
        
        public RemoveResponseBody(bool RemoveResult) {
            this.RemoveResult = RemoveResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface DatabaseWebServiceSoapChannel : _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.DatabaseWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class DatabaseWebServiceSoapClient : System.ServiceModel.ClientBase<_8_DatabaseWebService_RemoteDB._8_DatabaseWebService.DatabaseWebServiceSoap>, _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.DatabaseWebServiceSoap {
        
        public DatabaseWebServiceSoapClient() {
        }
        
        public DatabaseWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DatabaseWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int get_Size() {
            return base.Channel.get_Size();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.SearchResponse _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.DatabaseWebServiceSoap.Search(_8_DatabaseWebService_RemoteDB._8_DatabaseWebService.SearchRequest request) {
            return base.Channel.Search(request);
        }
        
        public _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.ArrayOfString[] Search(_8_DatabaseWebService_RemoteDB._8_DatabaseWebService.ArrayOfString keys) {
            _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.SearchRequest inValue = new _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.SearchRequest();
            inValue.Body = new _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.SearchRequestBody();
            inValue.Body.keys = keys;
            _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.SearchResponse retVal = ((_8_DatabaseWebService_RemoteDB._8_DatabaseWebService.DatabaseWebServiceSoap)(this)).Search(inValue);
            return retVal.Body.SearchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.EnterResponse _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.DatabaseWebServiceSoap.Enter(_8_DatabaseWebService_RemoteDB._8_DatabaseWebService.EnterRequest request) {
            return base.Channel.Enter(request);
        }
        
        public bool Enter(_8_DatabaseWebService_RemoteDB._8_DatabaseWebService.ArrayOfString tuple) {
            _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.EnterRequest inValue = new _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.EnterRequest();
            inValue.Body = new _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.EnterRequestBody();
            inValue.Body.tuple = tuple;
            _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.EnterResponse retVal = ((_8_DatabaseWebService_RemoteDB._8_DatabaseWebService.DatabaseWebServiceSoap)(this)).Enter(inValue);
            return retVal.Body.EnterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.RemoveResponse _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.DatabaseWebServiceSoap.Remove(_8_DatabaseWebService_RemoteDB._8_DatabaseWebService.RemoveRequest request) {
            return base.Channel.Remove(request);
        }
        
        public bool Remove(_8_DatabaseWebService_RemoteDB._8_DatabaseWebService.ArrayOfString keys) {
            _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.RemoveRequest inValue = new _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.RemoveRequest();
            inValue.Body = new _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.RemoveRequestBody();
            inValue.Body.keys = keys;
            _8_DatabaseWebService_RemoteDB._8_DatabaseWebService.RemoveResponse retVal = ((_8_DatabaseWebService_RemoteDB._8_DatabaseWebService.DatabaseWebServiceSoap)(this)).Remove(inValue);
            return retVal.Body.RemoveResult;
        }
    }
}
